//! Context-free patch representation ("ops"): the release kit ships our
//! patches as short operation lists per decomp file instead of unified diffs.
//! Per first-run-build.md ("Patches: legal note") a patch is a list of `=n`
//! (keep n pristine lines), `-n` (drop n) and `+text` (insert ours): the
//! pristine file is pinned by the decomp manifest hash (`manifest`), so no
//! context lines are needed for safety, and no decomp text beyond the
//! unavoidable `+` lines travels in our tree or the kit.

/// One operation over the pristine decomp file, applied in order.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Op {
    /// Copy `n` pristine lines verbatim.
    Keep(usize),
    /// Delete `n` pristine lines.
    Drop(usize),
    /// Append one of our lines.
    Insert(String),
}

/// Converts a unified diff (as generated by git) into ops. Mirrors
/// [`apply_unified_diff`]'s hunk parsing exactly (`@@ -a[,b]` headers,
/// `\ No newline` markers, hunks ended by the next `@@`/`--- `/`diff ` line),
/// but keeps only the structure: context and removed text are dropped, the
/// gap before every hunk becomes a leading [`Op::Keep`], and runs of
/// same-kind operations are coalesced. The hunk text is not verified here;
/// [`apply`] never needs it because the pristine file is hash-pinned.
/// Lines that git never emits inside a hunk are ignored (no old lines are
/// consumed), unlike [`apply_unified_diff`] which rejects them.
pub fn from_unified_diff(diff: &str) -> Vec<Op> {
    let mut ops: Vec<Op> = Vec::new();
    let mut pos = 0usize; // old lines consumed so far (end of the last op)
    let mut keep_run = 0usize; // consecutive context lines not yet emitted
    let mut drop_run = 0usize; // consecutive removals not yet emitted
    let mut lines = diff.lines().map(|l| l.trim_end_matches('\r')).peekable();
    while let Some(line) = lines.next() {
        let Some(rest) = line.strip_prefix("@@ -") else {
            continue; // `--- a/...`, `diff ...`, `index ...` and friends
        };
        // Same parsing as apply_unified_diff: old start before the first ','.
        let old_start: usize = rest
            .split([',', ' '])
            .next()
            .and_then(|n| n.parse().ok())
            .unwrap_or(0);
        let start = old_start.saturating_sub(1);
        flush_run(&mut ops, &mut keep_run, &mut drop_run);
        if start > pos {
            // Pristine lines before the first hunk / between hunks are kept
            // verbatim: the leading Keep at every hunk start.
            push_run(&mut ops, true, start - pos);
            pos = start;
        }
        while let Some(&h) = lines.peek() {
            if h.starts_with("@@") || h.starts_with("--- ") || h.starts_with("diff ") {
                break;
            }
            lines.next();
            if h.starts_with('\\') {
                continue; // "\ No newline at end of file"
            }
            let (tag, text) = h.split_at(h.len().min(1));
            match tag {
                " " | "" => {
                    if drop_run > 0 {
                        push_run(&mut ops, false, std::mem::take(&mut drop_run));
                    }
                    keep_run += 1;
                    pos += 1;
                }
                "-" => {
                    if keep_run > 0 {
                        push_run(&mut ops, true, std::mem::take(&mut keep_run));
                    }
                    drop_run += 1;
                    pos += 1;
                }
                "+" => {
                    flush_run(&mut ops, &mut keep_run, &mut drop_run);
                    ops.push(Op::Insert(text.to_string()));
                }
                _ => {} // never emitted by git inside a hunk; ignored
            }
        }
    }
    flush_run(&mut ops, &mut keep_run, &mut drop_run);
    ops
}

/// Applies ops to the pristine file. Old lines are consumed strictly in
/// order; lines past the last op are kept, so a trailing tail `Keep` is never
/// required. Line endings behave exactly like [`apply_unified_diff`]: every
/// line is CR-stripped and the output joins with the original's dominant EOL.
pub fn apply(original: &str, ops: &[Op]) -> Result<String, String> {
    let eol = if original.contains("\r\n") {
        "\r\n"
    } else {
        "\n"
    };
    let src: Vec<&str> = original.lines().map(|l| l.trim_end_matches('\r')).collect();
    let mut out: Vec<String> = Vec::new();
    let mut pos = 0usize; // next unconsumed line of `src`
    for (i, op) in ops.iter().enumerate() {
        match op {
            Op::Keep(n) => {
                let end = checked_end(pos, *n)
                    .ok_or_else(|| format!("op {i}: keep {n} overflows the line counter"))?;
                if end > src.len() {
                    return Err(format!("op {i}: keep {n} runs past the end of the file"));
                }
                out.extend(src[pos..end].iter().map(|s| s.to_string()));
                pos = end;
            }
            Op::Drop(n) => {
                let end = checked_end(pos, *n)
                    .ok_or_else(|| format!("op {i}: drop {n} overflows the line counter"))?;
                if end > src.len() {
                    return Err(format!("op {i}: drop {n} runs past the end of the file"));
                }
                pos = end;
            }
            Op::Insert(text) => out.push(text.clone()),
        }
    }
    out.extend(src[pos..].iter().map(|s| s.to_string()));
    let mut s = out.join(eol);
    s.push_str(eol);
    Ok(s)
}

/// Serialises one file's ops as the kit text format: a `file <path>` header
/// followed by one `=n` / `-n` / `+text` line per op. [`from_text`] is the
/// inverse. Insert text always follows the `+` tag, so even lines that look
/// like counts round-trip (`+` + `=5` serialises as `+=5`).
pub fn to_text(path: &str, ops: &[Op]) -> String {
    let mut s = format!("file {path}\n");
    for op in ops {
        match op {
            Op::Keep(n) => s.push_str(&format!("={n}\n")),
            Op::Drop(n) => s.push_str(&format!("-{n}\n")),
            Op::Insert(text) => s.push_str(&format!("+{text}\n")),
        }
    }
    s
}

/// Parses the kit text format produced by [`to_text`]: a list of `file <path>`
/// blocks, each carrying the ops for one decomp file, in order.
pub fn from_text(text: &str) -> Result<Vec<(String, Vec<Op>)>, String> {
    let mut files: Vec<(String, Vec<Op>)> = Vec::new();
    for (i, raw) in text.lines().enumerate() {
        let line = raw.trim_end_matches('\r');
        if line.is_empty() {
            continue;
        }
        let n = i + 1;
        if let Some(path) = line.strip_prefix("file ") {
            if path.is_empty() {
                return Err(format!("ops text line {n}: empty path"));
            }
            files.push((path.to_string(), Vec::new()));
            continue;
        }
        let Some(entry) = files.last_mut() else {
            return Err(format!(
                "ops text line {n}: op before any `file <path>` header"
            ));
        };
        let ops = &mut entry.1;
        if let Some(count) = line.strip_prefix('=') {
            ops.push(Op::Keep(parse_count(count).ok_or(format!(
                "ops text line {n}: `=n` needs a positive count"
            ))?));
        } else if let Some(count) = line.strip_prefix('-') {
            ops.push(Op::Drop(parse_count(count).ok_or(format!(
                "ops text line {n}: `-n` needs a positive count"
            ))?));
        } else if let Some(text) = line.strip_prefix('+') {
            ops.push(Op::Insert(text.to_string()));
        } else {
            return Err(format!(
                "ops text line {n}: expected `file <path>`, `=n`, `-n` or `+text`"
            ));
        }
    }
    Ok(files)
}

/// Appends a `Keep`/`Drop` of `n` lines, merging into an equal trailing op.
fn push_run(ops: &mut Vec<Op>, is_keep: bool, n: usize) {
    if n == 0 {
        return;
    }
    match ops.last_mut() {
        Some(Op::Keep(m)) if is_keep => *m += n,
        Some(Op::Drop(m)) if !is_keep => *m += n,
        _ => ops.push(if is_keep { Op::Keep(n) } else { Op::Drop(n) }),
    }
}

/// Emits both pending runs before an [`Op::Insert`] or hunk boundary; only
/// one of the two is ever nonzero (a context line after a removal first
/// emits the drop run).
fn flush_run(ops: &mut Vec<Op>, keep_run: &mut usize, drop_run: &mut usize) {
    push_run(ops, true, std::mem::take(keep_run));
    push_run(ops, false, std::mem::take(drop_run));
}

/// `pos + n` unless it would overflow.
fn checked_end(pos: usize, n: usize) -> Option<usize> {
    pos.checked_add(n)
}

/// A positive decimal count for `=n` / `-n`.
fn parse_count(digits: &str) -> Option<usize> {
    if digits.is_empty() || !digits.bytes().all(|b| b.is_ascii_digit()) {
        return None;
    }
    digits.parse().ok().filter(|n| *n > 0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::apply_unified_diff;

    #[test]
    fn ops_from_diff_structure() {
        // ctx, removal, two inserts, trailing context, second hunk: the gap
        // between hunks becomes a leading Keep, runs coalesce.
        let diff = "\
--- a/src/x.c
+++ b/src/x.c
@@ -3,4 +3,5 @@
 ctx
-del
+ours
+ours2
 keep
@@ -20,2 +22,3 @@
 more
";
        assert_eq!(
            from_unified_diff(diff),
            vec![
                Op::Keep(3), // gap of 2 + ctx, merged
                Op::Drop(1),
                Op::Insert("ours".into()),
                Op::Insert("ours2".into()),
                Op::Keep(16), // "keep" + gap to 20 + "more", all merged
            ]
        );
    }

    #[test]
    fn ops_match_unified_diff_on_a_synthetic_file() {
        // 22-line original, two hunks touching it: both appliers must agree.
        let original = (1..=22).map(|i| format!("L{i}\n")).collect::<String>();
        let diff = "\
@@ -3,6 +3,8 @@
 L3
 L4
-L5
+ours5
 L6
 L7
 L8
+inserted
@@ -20,2 +22,3 @@
 L20
 L21
+tail
";
        let ops = from_unified_diff(diff);
        let via_ops = apply(&original, &ops).unwrap();
        let via_diff = apply_unified_diff(&original, diff).unwrap();
        assert_eq!(via_ops.replace('\r', ""), via_diff.replace('\r', ""));
    }

    #[test]
    fn apply_rejects_ops_past_the_end() {
        assert!(apply("a\nb\n", &[Op::Keep(5)]).is_err());
        assert!(apply("a\nb\n", &[Op::Keep(1), Op::Drop(2)]).is_err());
        assert!(apply("", &[Op::Insert("x".into())]).is_ok());
    }

    #[test]
    fn ops_text_round_trip() {
        // Insert texts that look like counts, headers or tags must survive.
        let ops = vec![
            Op::Keep(3),
            Op::Drop(2),
            Op::Insert("=5".into()),
            Op::Insert("-12".into()),
            Op::Insert("file fake.c".into()),
            Op::Insert(String::new()),
            Op::Insert("++plus".into()),
        ];
        let text = to_text("src/x.c", &ops);
        assert_eq!(
            from_text(&text).unwrap(),
            vec![("src/x.c".to_string(), ops)]
        );
    }

    #[test]
    fn ops_text_rejects_junk() {
        assert!(from_text("=5").is_err()); // op before any file header
        assert!(from_text("file x.c\n=0").is_err());
        assert!(from_text("file x.c\n-x").is_err());
        assert!(from_text("file x.c\nctx").is_err());
        assert!(from_text("file x.c\n+ok").is_ok());
    }

    #[test]
    fn ops_text_accepts_crlf() {
        // The ops text may be written/read with CRLF line endings (Windows
        // checkout): identical parse to the LF form.
        let lf = to_text(
            "src/x.c",
            &[Op::Keep(2), Op::Drop(1), Op::Insert("ours".into())],
        );
        let crlf = lf.replace('\n', "\r\n");
        assert_eq!(from_text(&crlf).unwrap(), from_text(&lf).unwrap());
    }
}
