/* Rust functions the game DLL/.so calls (docs/notes/first-run-build.md).
 * One X(name) per line (Rust function `name`) and one C(name) per line
 * (CRT function thunked to Rust `pw64_crt_name`, pw64-platform crt.rs);
 * parsed by pw64-game build.rs (dylib feature) and compiled into
 * pw64_dll_shim.c. X = the static C archive's undefined symbols minus
 * ported.txt, CRT (ucrtbase/libc) and the shim's own data; with T1 the CRT
 * names route through thunks too, so the module imports nothing. */
X(__osGetCurrFaultedThread)
X(mio0_decompress)
X(osAiGetLength)
X(osAiSetFrequency)
X(osAiSetNextBuffer)
X(osContGetReadData)
X(osContInit)
X(osContStartReadData)
X(osCreateMesgQueue)
X(osCreatePiManager)
X(osCreateThread)
X(osCreateViManager)
X(osEepromLongRead)
X(osEepromLongWrite)
X(osEepromProbe)
X(osGetCount)
X(osInitialize)
X(osInvalDCache)
X(osPiRawReadIo)
X(osPiReadIo)
X(osPiStartDma)
X(osRecvMesg)
X(osSendMesg)
X(osSetEventMesg)
X(osSetIntMask)
X(osSetThreadPri)
X(osSetTimer)
X(osSpTaskLoad)
X(osSpTaskStartGo)
X(osSpTaskYield)
X(osSpTaskYielded)
X(osStartThread)
X(osViBlack)
X(osViGetCurrentFramebuffer)
X(osViGetNextFramebuffer)
X(osViSetEvent)
X(osViSetMode)
X(osViSetSpecialFeatures)
X(osViSwapBuffer)
X(osVirtualToPhysical)
X(osWritebackDCache)
X(osWritebackDCacheAll)
X(osYieldThread)
X(pw64_direct_start)
X(pw64_fatal)
X(pw64_fb_copy)
X(pw64_fb_pixels)
X(pw64_log)
X(pw64_present_active)
X(pw64_present_set_event)
X(pw64_swap)
C(ldiv)
C(memcpy)
C(memset)
C(powf)
C(sqrtf)
C(strlen)
